Traceback (most recent call last):
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Martin\anaconda3\envs\py37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\Martin\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pozidriv = mpimg.imread('images/pozi (1288).jpg')
kreuzschlitz = mpimg.imread('images/kreuzschlitz (1592).jpg')
philips = mpimg.imread('images/philips (1148).jpg')
innensechskant = mpimg.imread('images/innensechskant (1).jpg')
sechskant = mpimg.imread('images/sechskant (1334).jpg')
torx = mpimg.imread('images//torx (1178).jpg')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_11204/2056718158.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mpozidriv[0m [1;33m=[0m [0mmpimg[0m[1;33m.[0m[0mimread[0m[1;33m([0m[1;34m'images/pozi (1288).jpg'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mkreuzschlitz[0m [1;33m=[0m [0mmpimg[0m[1;33m.[0m[0mimread[0m[1;33m([0m[1;34m'images/kreuzschlitz (1592).jpg'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [0mphilips[0m [1;33m=[0m [0mmpimg[0m[1;33m.[0m[0mimread[0m[1;33m([0m[1;34m'images/philips (1148).jpg'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0minnensechskant[0m [1;33m=[0m [0mmpimg[0m[1;33m.[0m[0mimread[0m[1;33m([0m[1;34m'images/innensechskant (1).jpg'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0msechskant[0m [1;33m=[0m [0mmpimg[0m[1;33m.[0m[0mimread[0m[1;33m([0m[1;34m'images/sechskant (1334).jpg'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'mpimg' is not defined
NameError: name 'mpimg' is not defined

